In [1]:
import pandas as pd # still python but using code form people who wrote package "pandas'
import numpy as np # still python; used in context where calculations done rapidly is necessary
import matplotlib.pyplot as plt
import seaborn as sns

In [18]:
x= np.arange(12).reshape(3,4)
for row in x:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [10]:
pd.Series([0,1,2,3,4,5])

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

In [17]:
df=pd.DataFrame({
    'A':[1,2,3],
    'B':[4,5,6],
})

df['A']

#df.to_numpy()

#for _, row in df.iterrows():
#    print(row)

0    1
1    2
2    3
Name: A, dtype: int64

In [19]:
import holoviews